// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4a0WJNZkPBSwD0wH4li5nluoRWaW0jSE',
    appId: '1:735354648960:web:d6b70bef2ebff2b751a965',
    messagingSenderId: '735354648960',
    projectId: 'candle-in-dark',
    authDomain: 'candle-in-dark.firebaseapp.com',
    storageBucket: 'candle-in-dark.appspot.com',
    measurementId: 'G-8Y86VKM447',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0-JMEAjed-SEuvg4eS0OpRBzCClnDy6k',
    appId: '1:735354648960:android:d57bcad629db272651a965',
    messagingSenderId: '735354648960',
    projectId: 'candle-in-dark',
    storageBucket: 'candle-in-dark.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEwc0ch3xO075NjELkEIibeWsJbu2UlEw',
    appId: '1:735354648960:ios:e9d111c290da7f0e51a965',
    messagingSenderId: '735354648960',
    projectId: 'candle-in-dark',
    storageBucket: 'candle-in-dark.appspot.com',
    iosClientId: '735354648960-smauv79f82cvl20jsm71ls51qqrdli7e.apps.googleusercontent.com',
    iosBundleId: 'com.example.candleInDark',
  );
}